### ISSUE TITLE
License for project

### ISSUE THREAD

**Issue by suprafun** [MishaMengisen/JAMC#2]
Hello , I just arrived from watching a very cool Youtube video on your project. Under what license is your project released under ? I would like to study the code if you don't mind and learn about how you implemented some of the impressive features. Thank-you.

**Comment by MishaMengisen** [comment]
Creative commons - some credit would be nice. Have fun.

**Comment by MishaMengisen** [comment]
Added a Copyright.txt

**Comment by suprafun** [comment]
Hello Misha ,


Thank-you for including a license in your project. I am slightly confused though, the header of the license mentions " MIT COMMON CREATIVE LICENSE " but the text of the license is MIT.


The MIT license is a very generous license , but the " Creative Common " license is an entirely different family of licenses with different terms and conditions.


If it is alright with you I would like consider your project to be licensed under the MIT license. A very generous license and I thank-you for that :D

________________________________

**Comment by MishaMengisen** [comment]
Woops, you are very right. Let me change that. It is MIT license.

**Comment by suprafun** [comment]
Yes actually I did originally find the link to your video on a Reddit post , I think in GameDev , where you talked about voxel collision detection.
